---
name: MSc. Nidia
surname: Beltrán
position: "PhD"
address: "Morelos, México"
phone: +52 777-2354800
profilepic: nidia.jpg
email: "nidibelh@gmail.com"
twitter: Nidibelh
github: Nidibel
linkedin: nidia-beltranhz
date: "`r format(Sys.time(), '%B %Y')`"
aboutme: "I'm a PhD researcher in Biomedicine, Bioinformatics and Data Science, focused in omics analysis of cancer and chronic-degenerative diseases"
output: vitae::twentyseconds
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE, warning = FALSE, message = FALSE)
library(vitae)
```

# Skills

* Advanced knowledge in R and Bash shell scripting
* Intermediate knowledge in Python, Perl, Git
* Analysis of Next Generation Sequencing Data
* Molecular docking & Molecular Protein modeling
* Biochemistry, molecular biology, BigData and AI
* Languages: Spanish (Native), English (Advanced)
* Mendeley Advisor



# Education

```{r}
library(tibble)
tribble(
  ~ Degree, ~ Year, ~ Institution, ~ Where,
  "Bachelor in Biology", "2006-2010", "Universidad Autónoma del Estado de Morelos",  "México",
  "Master in Mol. Medicine", "2013-2015", "Universidad Autónoma del Estado de Morelos", "México",
  "PhD in Biochemistry", "2016 - 2021", "Universidad Nacional Autónoma de México", "México"
) %>% 
  detailed_entries(Degree, Year, Institution, Where)
```

# Experience

```{r}
tribble(
  ~Year, ~Type, ~Desc,
  1903, "Physics", "Awarded for her work on radioactivity with Pierre Curie and Henri Becquerel",
  1911, "Chemistry", "Awarded for the discovery of radium and polonium"
) %>% 
  brief_entries(
    glue::glue("Nobel Prize in {Type}"),
    Year, 
    Desc
  )
```

# Publications

```{r}
library(dplyr)
knitr::write_bib(c("vitae", "tibble"), "packages.bib")

bibliography_entries("packages.bib") %>%
  arrange(desc(author$family), issued)
```

